# Generated by Django 4.2.1 on 2023-05-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm_projects', '0005_alter_project_options_remove_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
    ]
