# Generated by Django 4.2.1 on 2023-05-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_users', '0003_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
